Make `upb_proto_aspect` reexport all `deps` when `srcs` is empty.
This special `proto_library` behavior is known as an *alias library*:
https://bazel.build/reference/be/protocol-buffer#proto_library_args

Without this CL, the compilation of the added test fails with:

```
test_import_empty_srcs.upb.c:12:10: error:
  module :test_import_empty_srcs_proto.upb does not depend on a
  module exporting 'test.upb.h'
```

PiperOrigin-RevId: 545153380