Remove unused `HasTopLevelEnums` function
This will address the following compilation error:

```
src/google/protobuf/compiler/python/python_generator.cc:95:13: warning: unused function 'HasTopLevelEnums' [-Wunused-function]
```